### ISSUE TITLE
Cloud Control API paginator support

### ISSUE THREAD

**Issue by jlhood** [benbridts/cloud-control-inventory#1]
@benbridts Just wanted to follow up and let you know [the latest boto3 supports paginators for Cloud Control API](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudcontrol.html#paginators) so [this workaround](https://github.com/benbridts/cloud-control-inventory/blob/main/src/botocore_data/cloudcontrol/2021-09-30/paginators-1.json) should no longer be necessary.

**Comment by benbridts** [comment]
Included the update, but forgot to say thanks.

Thanks!
